"use strict";

MZRUI.$setTemplate( "mzrui-fx-filter", () => [
	MZRUI.$createElement( "div", { class: "mzruiFxFilter-area mzruiFxFilter-areaType" },
		MZRUI.$createElement( "span", { class: "mzruiFxFilter-area-label" }, "type" ),
		MZRUI.$createElement( "div", { class: "mzruiFxFilter-area-content" },
			MZRUI.$getTemplate( "mzrui-fx-filter-type", "lowpass",   "M 1 4 L 12 4 L 15 8" ),
			MZRUI.$getTemplate( "mzrui-fx-filter-type", "highpass",  "M 1 8 L 4 4 L 15 4" ),
			MZRUI.$getTemplate( "mzrui-fx-filter-type", "bandpass",  "M 1 8 L 8 4 L 15 8" ),
			MZRUI.$getTemplate( "mzrui-fx-filter-type", "lowshelf",  "M 1 8 L 4 8 L 6 4 L 15 4" ),
			MZRUI.$getTemplate( "mzrui-fx-filter-type", "highshelf", "M 1 4 L 10 4 L 12 8 L 15 8" ),
			MZRUI.$getTemplate( "mzrui-fx-filter-type", "peaking",   "M 1 8 L 7 8 L 8 4 L 9 8 L 15 8" ),
			MZRUI.$getTemplate( "mzrui-fx-filter-type", "notch",     "M 1 4 L 7 4 L 8 8 L 9 4 L 15 4" ),
			MZRUI.$getTemplate( "mzrui-fx-filter-type", "allpass",   "M 1 6 L 15 6" ),
		),
	),
	MZRUI.$createElement( "div", { class: "mzruiFxFilter-area mzruiFxFilter-areaGraph" },
		MZRUI.$createElement( "span", { class: "mzruiFxFilter-area-label" }, "frequency" ),
		MZRUI.$createElement( "div", { class: "mzruiFxFilter-area-content" },
			MZRUI.$createElement( "mzrui-curves" ),
		),
	),
	MZRUI.$createElement( "div", { class: "mzruiFxFilter-area mzruiFxFilter-areaFrequency" },
		MZRUI.$createElement( "div", { class: "mzruiFxFilter-area-content" },
			MZRUI.$createElement( "mzrui-slider", { type: "linear-x", min: 0, max: 1, step: .0001, "data-prop": "frequency" } ),
		),
	),
	MZRUI.$createElement( "div", { class: "mzruiFxFilter-area mzruiFxFilter-areaGain" },
		MZRUI.$createElement( "span", { class: "mzruiFxFilter-area-label" }, "gain" ),
		MZRUI.$createElement( "div", { class: "mzruiFxFilter-area-content" },
			MZRUI.$createElement( "mzrui-slider", { type: "linear-y", min: -50, max: 50, step: .1, "mousemove-size": 400, "data-prop": "gain" } ),
		),
	),
	MZRUI.$createElement( "div", { class: "mzruiFxFilter-area mzruiFxFilter-areaQ" },
		MZRUI.$createElement( "span", { class: "mzruiFxFilter-area-label" }, "Q" ),
		MZRUI.$createElement( "div", { class: "mzruiFxFilter-area-content" },
			MZRUI.$createElement( "mzrui-slider", { type: "circular", min: .001, max: 25, step: .001, "mousemove-size": 400, "data-prop": "Q" } ),
		),
	),
	MZRUI.$createElement( "div", { class: "mzruiFxFilter-area mzruiFxFilter-areaDetune" },
		MZRUI.$createElement( "span", { class: "mzruiFxFilter-area-label" }, "detune" ),
		MZRUI.$createElement( "div", { class: "mzruiFxFilter-area-content" },
			MZRUI.$createElement( "mzrui-slider", { type: "circular", min: -1200, max: 1200, step: 10, "mousemove-size": 400, "data-prop": "detune" } ),
		),
	),
] );

MZRUI.$setTemplate( "mzrui-fx-filter-type", ( type, d ) =>
	MZRUI.$createElement( "button", { class: "mzruiFxFilter-areaType-btn", "data-type": type, title: type },
		MZRUI.$createElementSVG( "svg", { viewBox: "0 0 16 12" },
			MZRUI.$createElementSVG( "path", { d } ),
		),
	)
);
