"use strict";

MZRUI.$setTemplate( "mzrui-patterns-infoPopup", () =>
	MZRUI.$createElement( "div", { id: "mzruiPatterns-infoPopupContent" },
		MZRUI.$createElement( "fieldset", null,
			MZRUI.$createElement( "legend", null, "Type" ),
			MZRUI.$createElement( "label", null,
				MZRUI.$createElement( "input", { type: "radio", name: "type", value: "drum" } ),
				MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "buf-drum" } ),
				MZRUI.$createElement( "span", null, "drum" ),
			),
			MZRUI.$createElement( "label", null,
				MZRUI.$createElement( "input", { type: "radio", name: "type", value: "fx" } ),
				MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "buf-fx" } ),
				MZRUI.$createElement( "span", null, "fx" ),
			),
			MZRUI.$createElement( "label", null,
				MZRUI.$createElement( "input", { type: "radio", name: "type", value: "vocal" } ),
				MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "buf-vocal" } ),
				MZRUI.$createElement( "span", null, "vocal" ),
			),
			MZRUI.$createElement( "label", null,
				MZRUI.$createElement( "input", { type: "radio", name: "type", value: "loop" } ),
				MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "buf-loop" } ),
				MZRUI.$createElement( "span", null, "loop" ),
				MZRUI.$createElement( "span", null, "bpm" ),
				MZRUI.$createElement( "input", { class: "mzruiPopup-inputText", type: "number", name: "bpm", min: 1, max: 999.99, step: .01 } ),
			),
		),
		MZRUI.$createElement( "fieldset", null,
			MZRUI.$createElement( "legend", null, "Name" ),
			MZRUI.$createElement( "label", null,
				MZRUI.$createElement( "input", { class: "mzruiPopup-inputText", type: "text", name: "name" } ),
			),
		),
	)
);
