"use strict";

MZRUI.$setTemplate( "mzrui-daw-popup-shortcuts", () =>
	MZRUI.$createElement( "div", { class: "mzruiDAW-popup-shortcuts" },
		MZRUI.$createElement( "fieldset", null,
			MZRUI.$createElement( "legend", null, "Global shortcuts" ),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Save the current composition" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Ctrl / Alt" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "S" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Open a composition" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Ctrl / Alt" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "O" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Open a new composition" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Alt" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "N" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Play / pause the selected grid" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Space" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Undo the previous action" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Ctrl / Alt" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "Z" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Redo the next action" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Ctrl / Alt" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "Shift" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "Z" ),
				),
			),
		),
		MZRUI.$createElement( "fieldset", null,
			MZRUI.$createElement( "legend", null, "Grids shortcuts" ),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Select all the blocks of the focused grid" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Ctrl / Alt" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "A" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Deselect all the blocks of the focused grid" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Ctrl / Alt" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "D" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Duplicate (copy/paste) the selected blocks" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Ctrl / Alt" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null, "B" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Delete all the selected blocks of the focused grid" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Delete" ),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Move vertically inside the grids" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null,
						"Scroll ",
						MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Move horizontally inside the grids" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Shift" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null,
						"Scroll ",
						MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" },
					"Zoom-in / zoom-out", MZRUI.$createElement( "br" ),
					"Zoom X by scrolling above the grid", MZRUI.$createElement( "br" ),
					"Zoom Y by scrolling above the keys", MZRUI.$createElement( "br" ),
				),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "kbd", null, "Ctrl / ⌘" ),
					MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "plus" } ),
					MZRUI.$createElement( "kbd", null,
						"Scroll ",
						MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
		),
	)
);
