"use strict";

MZRUI.$setTemplate( "mzrui-daw-popup-settings", () =>
	MZRUI.$createElement( "div", { class: "mzruiDAW-popup-settings" },
		MZRUI.$createElement( "fieldset", null,
			MZRUI.$createElement( "legend", null, "Audio" ),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Feedback sample rate" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "select", { name: "sampleRate" },
						MZRUI.$createElement( "option", { value: 8000 }, "8 kHz" ),
						MZRUI.$createElement( "option", { value: 11025 }, "11.025 kHz" ),
						MZRUI.$createElement( "option", { value: 12000 }, "12 kHz" ),
						MZRUI.$createElement( "option", { value: 22050 }, "22.05 kHz" ),
						MZRUI.$createElement( "option", { value: 24000 }, "24 kHz" ),
						MZRUI.$createElement( "option", { value: 44100 }, "44.1 kHz" ),
						MZRUI.$createElement( "option", { value: 48000, style: "font-weight:bold" }, "48 kHz" ),
						MZRUI.$createElement( "option", { value: 88200 }, "88.2 kHz" ),
						MZRUI.$createElement( "option", { value: 96000 }, "96 kHz" ),
					),
				),
			),
		),
		MZRUI.$createElement( "fieldset", null,
			MZRUI.$createElement( "legend", null, "UI refresh rate" ),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Auto" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "label", null,
						MZRUI.$createElement( "input", { name: "uiRate", type: "radio", value: "auto" } ),
						MZRUI.$createElement( "span", { class: "mzruiDAW-uiRateFps" }, 60 ),
					),
				),
			),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Manual" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "label", null,
						MZRUI.$createElement( "input", { name: "uiRate", type: "radio", value: "manual" } ),
						MZRUI.$createElement( "span", { class: "mzruiDAW-uiRateFps" }, 40 ),
					),
					MZRUI.$createElement( "input", { name: "uiRateFPS", type: "range", step: 1, min: 5, max: 40, value: 40 } ),
				),
			),
		),
		MZRUI.$createElement( "fieldset", null,
			MZRUI.$createElement( "legend", null, "Windows" ),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Move/resize mode" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "label", null,
						MZRUI.$createElement( "input", { name: "windowsLowGraphics", type: "checkbox" } ),
						MZRUI.$createElement( "span", null, "low graphic" ),
					),
				),
			),
		),
		MZRUI.$createElement( "fieldset", null,
			MZRUI.$createElement( "legend", null, "Timeline" ),
			MZRUI.$createElement( "div", { class: "mzruiPopup-row" },
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-title" }, "Numbering measures starting at" ),
				MZRUI.$createElement( "div", { class: "mzruiPopup-row-values" },
					MZRUI.$createElement( "select", { name: "timelineNumbering" },
						MZRUI.$createElement( "option", { value: 0 }, 0 ),
						MZRUI.$createElement( "option", { value: 1 }, 1 ),
					),
				),
			),
		),
	)
);
