"use strict";

MZRUI.$setTemplate( "mzrui-timewindow", () => [
	MZRUI.$createElement( "div", { class: "mzruiTimewindow-panel" },
		MZRUI.$createElement( "div", { class: "mzruiTimewindow-panelUp" },
			MZRUI.$createElement( "button", { class: "mzruiTimewindow-step" },
				MZRUI.$createElement( "span", { class: "mzruiTimewindow-stepValue" } ),
				MZRUI.$createElement( "i", { class: "mzruiIcon", "data-icon": "magnet" } ),
			),
		),
		MZRUI.$createElement( "div", { class: "mzruiTimewindow-panelContent" } ),
		MZRUI.$createElement( "div", { class: "mzruiTimewindow-panelContentDown" },
			MZRUI.$createElement( "div", { class: "mzruiTimewindow-panelExtend mzruiTimewindow-panelExtendX" } ),
		),
		MZRUI.$createElement( "div", { class: "mzruiTimewindow-panelExtend mzruiTimewindow-panelExtendY" } ),
	),
	MZRUI.$createElement( "div", { class: "mzruiTimewindow-main" },
		MZRUI.$createElement( "div", { class: "mzruiTimewindow-time" },
			MZRUI.$createElement( "mzrui-timeline" ),
		),
		MZRUI.$createElement( "div", { class: "mzruiTimewindow-mainBody" },
			MZRUI.$createElement( "div", { class: "mzruiTimewindow-mainContent" },
				MZRUI.$createElement( "mzrui-beatlines", { coloredbeats: "" } ),
				MZRUI.$createElement( "div", { class: "mzruiTimewindow-currentTime" } ),
				MZRUI.$createElement( "div", { class: "mzruiTimewindow-loop mzruiTimewindow-loopA" } ),
				MZRUI.$createElement( "div", { class: "mzruiTimewindow-loop mzruiTimewindow-loopB" } ),
				MZRUI.$createElement( "div", { class: "mzruiTimewindow-rows" } ),
			),
		),
		MZRUI.$createElement( "div", { class: "mzruiTimewindow-contentDown" },
			MZRUI.$createElement( "div", { class: "mzruiTimewindow-panelExtend mzruiTimewindow-panelExtendX" } ),
		),
	),
] );
